[project]
name = "chat-litellm-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "litellm[proxy]>=1.79.1",
    "openai>=2.7.1",
]
