model_list:
  - model_name: "my-custom-qwen3-0.6b"
    litellm_params:
      model: my-custom-llm/ollama/qwen3:0.6b
      api_base: http://0.0.0.0:11434
      api_key: "openai key"
  - model_name: "my-custom-gpt-5-nano"
    litellm_params:
      model: my-custom-llm/openai/gpt-5-nano
      api_key: os.environ/OPENAI_API_KEY
  - model_name: qwen3-0.6b
    litellm_params:
      model: ollama/qwen3:0.6b
      api_base: http://0.0.0.0:11434
      api_key: "openai key"
  - model_name: gpt-5-nano
    litellm_params:
      model: openai/gpt-5-nano
      api_key: os.environ/OPENAI_API_KEY

litellm_settings:
  custom_provider_map:
    - provider: "my-custom-llm"
      custom_handler: agent.my_custom_llm

general_settings:
  master_key: sk-1234
